-- Create 3 MSE Products for CreditConnect Tenant
-- Currency: BWP, Interest: 7% per month (Flat), Bullet Payment, 1-4 months term

-- 1. MSE Purchase Order Finance (MPOF)
INSERT INTO credit_connect_db.m_product_loan (
  short_name, currency_code, currency_digits, currency_multiplesof,
  principal_amount, min_principal_amount, max_principal_amount, arrearstolerance_amount,
  name, description, fund_id, is_linked_to_floating_interest_rates, allow_variabe_installments,
  nominal_interest_rate_per_period, min_nominal_interest_rate_per_period, max_nominal_interest_rate_per_period,
  interest_period_frequency_enum, annual_nominal_interest_rate, interest_method_enum,
  interest_calculated_in_period_enum, allow_partial_period_interest_calcualtion,
  repay_every, repayment_period_frequency_enum, number_of_repayments,
  min_number_of_repayments, max_number_of_repayments, grace_on_principal_periods,
  recurring_moratorium_principal_periods, grace_on_interest_periods, grace_interest_free_periods,
  amortization_method_enum, accounting_type, loan_transaction_strategy_id,
  external_id, include_in_borrower_cycle, use_borrower_cycle, start_date, close_date,
  allow_multiple_disbursals, max_disbursals, max_outstanding_loan_balance,
  grace_on_arrears_ageing, overdue_days_for_npa, days_in_month_enum, days_in_year_enum,
  interest_recalculation_enabled, min_days_between_disbursal_and_first_repayment,
  hold_guarantee_funds, principal_threshold_for_last_installment,
  account_moves_out_of_npa_only_on_arrears_completion, can_define_fixed_emi_amount,
  instalment_amount_in_multiples_of, can_use_for_topup, sync_expected_with_disbursement_date,
  is_equal_amortization, fixed_principal_percentage_per_installment,
  disallow_expected_disbursements, allow_approved_disbursed_amounts_over_applied,
  over_applied_calculation_type, over_applied_number, delinquency_bucket_id,
  loan_transaction_strategy_code, loan_transaction_strategy_name,
  due_days_for_repayment_event, overdue_days_for_repayment_event, enable_down_payment,
  disbursed_amount_percentage_for_down_payment, enable_installment_level_delinquency,
  enable_accrual_activity_posting, enable_auto_repayment_for_down_payment,
  repayment_start_date_type_enum, loan_schedule_type, loan_schedule_processing_type,
  fixed_length, supported_interest_refund_types, charge_off_behaviour,
  interest_recognition_on_disbursement_date
) VALUES (
  'MPOF', 'BWP', 2, NULL,
  50000.000000, 5000.000000, 1000000.000000, NULL,
  'MSE Purchase Order Finance', 'Short-term funding to help purchase orders before value upfront to procure the product. Ideal for short-term liquidity & fixed revenue for the delivered product', NULL, 0, 0,
  7.000000, 7.000000, 7.000000,
  3, 84.000000, 1,
  1, 0,
  1, 2, 1,
  1, 4, 1,
  NULL, NULL, NULL,
  1, 3, NULL,
  NULL, 0, 0, NOW(), NULL,
  0, NULL, NULL,
  NULL, NULL, 30, 360,
  0, NULL,
  0, 0.00,
  0, 0,
  NULL, 0, 0,
  0, 100.00,
  0, 0,
  NULL, NULL, 5,
  'mifos-standard-strategy', 'Penalties, Fees, Interest, Principal order',
  NULL, NULL, 0,
  NULL, 0,
  0, 0,
  1, 'CUMULATIVE', 'HORIZONTAL',
  NULL, NULL, 'REGULAR',
  0
);

-- 2. MSE Invoice Discounting (MIDF)
INSERT INTO credit_connect_db.m_product_loan (
  short_name, currency_code, currency_digits, currency_multiplesof,
  principal_amount, min_principal_amount, max_principal_amount, arrearstolerance_amount,
  name, description, fund_id, is_linked_to_floating_interest_rates, allow_variabe_installments,
  nominal_interest_rate_per_period, min_nominal_interest_rate_per_period, max_nominal_interest_rate_per_period,
  interest_period_frequency_enum, annual_nominal_interest_rate, interest_method_enum,
  interest_calculated_in_period_enum, allow_partial_period_interest_calcualtion,
  repay_every, repayment_period_frequency_enum, number_of_repayments,
  min_number_of_repayments, max_number_of_repayments, grace_on_principal_periods,
  recurring_moratorium_principal_periods, grace_on_interest_periods, grace_interest_free_periods,
  amortization_method_enum, accounting_type, loan_transaction_strategy_id,
  external_id, include_in_borrower_cycle, use_borrower_cycle, start_date, close_date,
  allow_multiple_disbursals, max_disbursals, max_outstanding_loan_balance,
  grace_on_arrears_ageing, overdue_days_for_npa, days_in_month_enum, days_in_year_enum,
  interest_recalculation_enabled, min_days_between_disbursal_and_first_repayment,
  hold_guarantee_funds, principal_threshold_for_last_installment,
  account_moves_out_of_npa_only_on_arrears_completion, can_define_fixed_emi_amount,
  instalment_amount_in_multiples_of, can_use_for_topup, sync_expected_with_disbursement_date,
  is_equal_amortization, fixed_principal_percentage_per_installment,
  disallow_expected_disbursements, allow_approved_disbursed_amounts_over_applied,
  over_applied_calculation_type, over_applied_number, delinquency_bucket_id,
  loan_transaction_strategy_code, loan_transaction_strategy_name,
  due_days_for_repayment_event, overdue_days_for_repayment_event, enable_down_payment,
  disbursed_amount_percentage_for_down_payment, enable_installment_level_delinquency,
  enable_accrual_activity_posting, enable_auto_repayment_for_down_payment,
  repayment_start_date_type_enum, loan_schedule_type, loan_schedule_processing_type,
  fixed_length, supported_interest_refund_types, charge_off_behaviour,
  interest_recognition_on_disbursement_date
) VALUES (
  'MIDF', 'BWP', 2, NULL,
  50000.000000, 5000.000000, 1000000.000000, NULL,
  'MSE Invoice Discounting', 'An advance provided against an unpaid customer invoice. A portion of the invoice value upfront to improve the business cash flow. The lender receives a fee & settles the invoice', NULL, 0, 0,
  7.000000, 7.000000, 7.000000,
  3, 84.000000, 1,
  1, 0,
  1, 2, 1,
  1, 4, 1,
  NULL, NULL, NULL,
  1, 3, NULL,
  NULL, 0, 0, NOW(), NULL,
  0, NULL, NULL,
  NULL, NULL, 30, 360,
  0, NULL,
  0, 0.00,
  0, 0,
  NULL, 0, 0,
  0, 100.00,
  0, 0,
  NULL, NULL, 5,
  'mifos-standard-strategy', 'Penalties, Fees, Interest, Principal order',
  NULL, NULL, 0,
  NULL, 0,
  0, 0,
  1, 'CUMULATIVE', 'HORIZONTAL',
  NULL, NULL, 'REGULAR',
  0
);

-- 3. MSE Working Capital Finance (MWCF)
INSERT INTO credit_connect_db.m_product_loan (
  short_name, currency_code, currency_digits, currency_multiplesof,
  principal_amount, min_principal_amount, max_principal_amount, arrearstolerance_amount,
  name, description, fund_id, is_linked_to_floating_interest_rates, allow_variabe_installments,
  nominal_interest_rate_per_period, min_nominal_interest_rate_per_period, max_nominal_interest_rate_per_period,
  interest_period_frequency_enum, annual_nominal_interest_rate, interest_method_enum,
  interest_calculated_in_period_enum, allow_partial_period_interest_calcualtion,
  repay_every, repayment_period_frequency_enum, number_of_repayments,
  min_number_of_repayments, max_number_of_repayments, grace_on_principal_periods,
  recurring_moratorium_principal_periods, grace_on_interest_periods, grace_interest_free_periods,
  amortization_method_enum, accounting_type, loan_transaction_strategy_id,
  external_id, include_in_borrower_cycle, use_borrower_cycle, start_date, close_date,
  allow_multiple_disbursals, max_disbursals, max_outstanding_loan_balance,
  grace_on_arrears_ageing, overdue_days_for_npa, days_in_month_enum, days_in_year_enum,
  interest_recalculation_enabled, min_days_between_disbursal_and_first_repayment,
  hold_guarantee_funds, principal_threshold_for_last_installment,
  account_moves_out_of_npa_only_on_arrears_completion, can_define_fixed_emi_amount,
  instalment_amount_in_multiples_of, can_use_for_topup, sync_expected_with_disbursement_date,
  is_equal_amortization, fixed_principal_percentage_per_installment,
  disallow_expected_disbursements, allow_approved_disbursed_amounts_over_applied,
  over_applied_calculation_type, over_applied_number, delinquency_bucket_id,
  loan_transaction_strategy_code, loan_transaction_strategy_name,
  due_days_for_repayment_event, overdue_days_for_repayment_event, enable_down_payment,
  disbursed_amount_percentage_for_down_payment, enable_installment_level_delinquency,
  enable_accrual_activity_posting, enable_auto_repayment_for_down_payment,
  repayment_start_date_type_enum, loan_schedule_type, loan_schedule_processing_type,
  fixed_length, supported_interest_refund_types, charge_off_behaviour,
  interest_recognition_on_disbursement_date
) VALUES (
  'MWCF', 'BWP', 2, NULL,
  50000.000000, 5000.000000, 1000000.000000, NULL,
  'MSE Working Capital Finance', 'Flexible short-term loan to cover operational expenses like salaries, rent, inventory, stock, and equipment. Repayments through sales revenue or cash flow', NULL, 0, 0,
  7.000000, 7.000000, 7.000000,
  3, 84.000000, 1,
  1, 0,
  1, 2, 1,
  1, 4, 1,
  NULL, NULL, NULL,
  1, 3, NULL,
  NULL, 0, 0, NOW(), NULL,
  0, NULL, NULL,
  NULL, NULL, 30, 360,
  0, NULL,
  0, 0.00,
  0, 0,
  NULL, 0, 0,
  0, 100.00,
  0, 0,
  NULL, NULL, 5,
  'mifos-standard-strategy', 'Penalties, Fees, Interest, Principal order',
  NULL, NULL, 0,
  NULL, 0,
  0, 0,
  1, 'CUMULATIVE', 'HORIZONTAL',
  NULL, NULL, 'REGULAR',
  0
);
