#!/bin/bash
echo "🚀 Manual Deployment Instructions for Admin Portal"
echo "================================================="
echo ""
echo "STEP 1: Deploy ESS Backend (135.181.33.13)"
echo "-------------------------------------------"
echo "ssh uswege@135.181.33.13"
echo "cd /home/uswege/ess"
echo "git pull origin main"
echo "npm install"
echo "pm2 restart all"
echo "pm2 status"
echo ""
echo "STEP 2: Test Backend API (from your local machine)"
echo "------------------------------------------------"
echo "curl -X GET http://135.181.33.13:3002/health"
echo "curl -X GET http://135.181.33.13:3002/api/v1/loan/list-products"
echo ""
echo "STEP 3: Update Admin Portal Frontend (5.75.185.137)"
echo "--------------------------------------------------"
echo "ssh uswege@5.75.185.137"
echo "cd /opt/middleware/MiraAdmin"
echo ""
echo "# Create the React app structure"
echo "mkdir -p frontend/src/components frontend/src/services"
echo ""
echo "# Copy the React components we created"
echo "# (Files are in the ESS repo under frontend/ directory)"
echo ""
echo "STEP 4: Quick Fix - Update Current Portal"
echo "---------------------------------------"
echo "# For immediate fix, update the existing loan page to fetch from ESS backend"
echo "# Replace static data with API call to: http://135.181.33.13:3002/api/v1/loan/list-employee-loan"